[global]
server = "whois.radb.net:43"
sources = ["RADB", "RIPE", "APNIC"]
aggregate  = true  # default = true
timestamps = true  # default = false
outputdir = "./output"

[[routers]]
hostname = "xr-router"
style = "prefix-set"
filters = [
  "AS-RIPENCC",
  "AS3333",
]

[[routers]]
hostname = "ios-router"
style = "prefix-list"
filters = [
  "AS-RIPENCC",
  "AS3333",
]

